language: node_js
notifications:
  email: false
sudo: false
node_js:
  - "4.8.1"
cache:
  directories:
    - node_modules

before_install:
  - git clone https://github.com/EDCD/coriolis-data.git ../coriolis-data

script:
  - npm run lint
  - npm test
